spring.application.name=kiosk

# ?? ??
server.port=8083

# ?? ??
logging.level.root=INFO
logging.level.com.kiosk=DEBUG
logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n

# Thymeleaf ??
spring.thymeleaf.cache=false
spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html

# ?? ??? ?? (???)
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

# WebSocket ??
spring.websocket.sockjs.client-library-url=https://cdnjs.cloudflare.com/ajax/libs/sockjs-client/1.6.1/sockjs.min.js